// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeSwitch: typeof import('./src/components/DarkModeSwitch.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    PageWrapper: typeof import('./src/components/PageWrapper.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
